repos:
  - repo: local
    hooks:  # Corrigido de "hools" para "hooks"
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
          "-rn",
          "-sn",
          "--rcfile=.pylintrc",
          "--load-plugins=pylint.extensions.docparams",
        ]